name: notify-mastodon
on: [push]
jobs:
  twt:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: mwyolyfrau/peiriant/.github/workflows/post-to-mastodon.yml@main
    with: 
      status: "This is a test"
      
