name: notify-mastodon
on: [push]
jobs:
  chk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: git log
        shell: pwsh
        id: glog
        run: |
          $var = $(git log -n 1)
          write-output $var
  twt:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: mwyolyfrau/peiriant/.github/workflows/post-to-mastodon.yml@main
    with:  
      status: "This is a test post from the WrP repo"
      
